# Podfile
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'
target 'WJEduiOS' do
    pod 'RxSwift',    '~> 3.0'
    pod 'RxCocoa',    '~> 3.0'
    pod 'Moya', '8.0.0-beta.5'
    pod 'Moya/RxSwift'
    pod 'SnapKit', '~> 3.0.2'
    pod 'Kingfisher', '~> 3.0'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'
    pod 'ObjectMapper'
    pod 'Validator', git: 'https://github.com/adamwaite/Validator.git', tag: 'v2.0.0'
    pod 'KRProgressHUD'
    pod 'RxDataSources', '~> 1.0'
    # pod 'HandyJSON', '~> 1.3.0'
#    pod 'SwiftyJSON', '~> 3.0.0'
    pod 'SwiftyJSON', :git =>'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'RealmSwift'
    pod 'CryptoSwift'

end

# RxTests and RxBlocking make the most sense in the context of unit/integration tests
target 'WJEduiOSTests' do

    pod 'RxBlocking', '~> 3.0'
    pod 'RxTest',     '~> 3.0'
end
